service: telegram-bot-tenko

frameworkVersion: "2"
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  memorySize: 128
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    TENKO_API_URI: ${env:TENKO_API_URI}
    TENKO_API_TOKEN: ${env:TENKO_API_TOKEN}
    USER_NAME: ${env:USER_NAME}

functions:
  tenkobot:
    handler: handler.tenkobot
    events:
      - http:
          path: tenko-bot
          method: post
          cors: true
  totalStat:
    handler: handler.totalStat
    events:
      - schedule:
          rate: cron(0 0 * * ? *)
          timezone: Europe/Kiev
      - schedule:
          rate: cron(0 7 * * ? *)
          timezone: Europe/Kiev
      - schedule:
          rate: cron(0 23 * * ? *)
          timezone: Europe/Kiev
  writeStat:
    handler: handler.writeStat

plugins:
  - serverless-local-schedule
